### ISSUE TITLE
固定比例能不能也可以允许8个方向，类似微信头像裁剪那样

### ISSUE THREAD

**Issue by Lius1104** [Rogue24/JPImageresizerView#11]

**Comment by Rogue24** [comment]
微信应该是最近更新的吧 以前我没发现 好的 我今晚就加上

发自我的iPhone

在 2019年12月4日，上午10:48，Lius1104 <notifications@github.com> 写道：

﻿

**Comment by Rogue24** [comment]
1.2.0版本已添加✌🏼

发自我的iPhone

在 2019年12月4日，上午10:48，Lius1104 <notifications@github.com> 写道：

﻿
