### ISSUE TITLE
设置自定义裁剪框，旋转的时候能不能只旋转图片不旋转裁剪框

### ISSUE THREAD

**Issue by Lius1104** [Rogue24/JPImageresizerView#12]
我的自定义裁剪框图片上面有一个头像的虚线框，旋转的时候因为FrameView 跟着一起旋转了，所以 头像的虚框就不是正着的了

**Comment by Rogue24** [comment]
是的。。裁剪框也是一起旋转的。。

**Comment by Lius1104** [comment]
能处理一下吗，我现在把裁剪框上的头像虚线框单独切了个图加到了frameView 上旋转的时候隐藏旋转完出现 但是有一点问题是我拖拽缩小裁剪框复原后头像虚线的frame会比裁剪框更快更新会出现裁剪框小头像虚框大的一个动画过程

**Comment by Rogue24** [comment]
可以加我扣扣录个屏给我瞧瞧咩
