### ISSUE TITLE
有问题想请求一下

### ISSUE THREAD

**Issue by Temozly** [Rogue24/JPImageresizerView#13]
这个是用IOS版本的实现，我对IOS不算懂，但是现在是有一个需求，用Unity来实现，不知道楼主知道怎么实现吗？可以说下大致思路吗？只需要裁剪那一部分，自由拖拽，然后裁剪图片

**Comment by Rogue24** [comment]
﻿抱歉了……我对Unity不太了解

发自我的iPhone

在 2020年1月15日，下午10:17，Temozly <notifications@github.com> 写道：

﻿

这个是用IOS版本的实现，我对IOS不算懂，但是现在是有一个需求，用Unity来实现，不知道楼主知道怎么实现吗？可以说下大致思路吗？只需要裁剪那一部分，自由拖拽，然后裁剪图片

**Comment by Temozly** [comment]
那能说一下，你实现裁剪的思路吗？具体怎么计算裁剪框拖拽之后，再回弹的大小和位置，以及和下面被裁剪的图片的缩放是什么样的对应关系，就是怎么根据你拖拽之后的裁剪框的大小，计算相应的被裁剪的图片的大小，拖拽之后回弹的大小是通过什么样的方式来计算的

**Comment by Rogue24** [comment]
这些苹果都有对应的API，最主要是坐标转换

发自我的iPhone

在 2020年1月16日，下午6:37，Temozly <notifications@github.com> 写道：

﻿

那能说一下，你实现裁剪的思路吗？具体怎么计算裁剪框拖拽之后，再回弹的大小和位置，以及和下面被裁剪的图片的缩放是什么样的对应关系，就是怎么根据你拖拽之后的裁剪框的大小，计算相应的被裁剪的图片的大小，拖拽之后回弹的大小是通过什么样的方式来计算的
