### ISSUE TITLE
Swift版好久出来呢？

### ISSUE THREAD

**Issue by qinling01** [Rogue24/JPImageresizerView#14]
Swift版好久出来呢？

**Comment by Rogue24** [comment]
很抱歉现在才回复 最近在忙着找工作 另外由于swift我还没摸透 所以只做了一半 实在很抱歉！

发自我的iPhone

在 2020年3月27日，下午3:28，qinling01 <notifications@github.com> 写道：

﻿

Swift版好久出来呢？
