### ISSUE TITLE
能否适配下横屏的时候，横屏时候问题好多，滑动不顺畅

### ISSUE THREAD

**Issue by asfisker** [Rogue24/JPImageresizerView#16]
最新版本已经适配横竖屏切换！

**Comment by Rogue24** [comment]
嗯嗯 好的 因为目前只针对了竖屏情况 抱歉

发自我的iPhone

在 2020年5月11日，下午8:45，asfisker <notifications@github.com> 写道：

﻿

**Comment by Rogue24** [comment]
最新版本已经适配横竖屏切换~
