### ISSUE TITLE
裁剪有留白的情况

### ISSUE THREAD

**Issue by taozl** [Rogue24/JPImageresizerView#19]
在xsMax手机上进行裁剪横图的时候，出现裁剪后的图片有留白的情况。
目测代码：
// 获取裁剪区域
            CGFloat imageScale = resultImage.scale;
            CGFloat imageWidth = resultImage.size.width;
            CGFloat imageHeight = resultImage.size.height;
            CGFloat cropX = imageWidth * (cropFrame.origin.x / relativeSize.width);
            CGFloat cropY = imageHeight * (cropFrame.origin.y / relativeSize.height);
            CGFloat cropW = imageWidth * (cropFrame.size.width / relativeSize.width);
            CGFloat cropH = imageHeight * (cropFrame.size.height / relativeSize.height);

这里的cropW和cropH的裁剪区域过大。我不确定是不是精度丢失导致的。

**Comment by Rogue24** [comment]
收到 会尽快解决

发自我的iPhone

在 2020年6月17日，下午5:36，taozl <notifications@github.com> 写道：

﻿

在xsMax手机上进行裁剪横图的时候，出现裁剪后的图片有留白的情况。
目测代码：
// 获取裁剪区域
CGFloat imageScale = resultImage.scale;
CGFloat imageWidth = resultImage.size.width;
CGFloat imageHeight = resultImage.size.height;
CGFloat cropX = imageWidth * (cropFrame.origin.x / relativeSize.width);
CGFloat cropY = imageHeight * (cropFrame.origin.y / relativeSize.height);
CGFloat cropW = imageWidth * (cropFrame.size.width / relativeSize.width);
CGFloat cropH = imageHeight * (cropFrame.size.height / relativeSize.height);

这里的cropW和cropH的裁剪区域过大。我不确定是不是精度丢失导致的。

**Comment by Rogue24** [comment]
能否提供一下你的图片呢

发自我的iPhone

在 2020年6月17日，下午6:19，周 健平 <zhoujianping24@hotmail.com> 写道：

﻿ 收到 会尽快解决

发自我的iPhone

在 2020年6月17日，下午5:36，taozl <notifications@github.com> 写道：

﻿

在xsMax手机上进行裁剪横图的时候，出现裁剪后的图片有留白的情况。
目测代码：
// 获取裁剪区域
CGFloat imageScale = resultImage.scale;
CGFloat imageWidth = resultImage.size.width;
CGFloat imageHeight = resultImage.size.height;
CGFloat cropX = imageWidth * (cropFrame.origin.x / relativeSize.width);
CGFloat cropY = imageHeight * (cropFrame.origin.y / relativeSize.height);
CGFloat cropW = imageWidth * (cropFrame.size.width / relativeSize.width);
CGFloat cropH = imageHeight * (cropFrame.size.height / relativeSize.height);

这里的cropW和cropH的裁剪区域过大。我不确定是不是精度丢失导致的。

**Comment by Rogue24** [comment]
你好 我更新了一个小版本 你可以更新试试看是否已经解决这个问题

发自我的iPhone

在 2020年6月17日，下午6:19，周 健平 <zhoujianping24@hotmail.com> 写道：

﻿ 收到 会尽快解决

发自我的iPhone

在 2020年6月17日，下午5:36，taozl <notifications@github.com> 写道：

﻿

在xsMax手机上进行裁剪横图的时候，出现裁剪后的图片有留白的情况。
目测代码：
// 获取裁剪区域
CGFloat imageScale = resultImage.scale;
CGFloat imageWidth = resultImage.size.width;
CGFloat imageHeight = resultImage.size.height;
CGFloat cropX = imageWidth * (cropFrame.origin.x / relativeSize.width);
CGFloat cropY = imageHeight * (cropFrame.origin.y / relativeSize.height);
CGFloat cropW = imageWidth * (cropFrame.size.width / relativeSize.width);
CGFloat cropH = imageHeight * (cropFrame.size.height / relativeSize.height);

这里的cropW和cropH的裁剪区域过大。我不确定是不是精度丢失导致的。
