### ISSUE TITLE
有支持微调旋转吗？

### ISSUE THREAD

**Issue by ZFbaby** [Rogue24/JPImageresizerView#20]
任意角度旋转可以支持吗

**Comment by Rogue24** [comment]
这个计算略复杂 研究中

发自我的iPhone

在 2020年6月23日，下午3:34，daizeng.yang <notifications@github.com> 写道：

﻿

任意角度旋转可以支持吗

**Comment by ZFbaby** [comment]
好的，谢谢啦





------------------ 原始邮件 ------------------
发件人: 健了个平 <notifications@github.com&gt;
发送时间: 2020年6月23日 18:12
收件人: Rogue24/JPImageresizerView <JPImageresizerView@noreply.github.com&gt;
抄送: daizeng.yang <316917975@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Rogue24/JPImageresizerView] 有支持微调旋转吗？ (#20)

**Comment by Rogue24** [comment]
抱歉啦 最近被催着发版

发自我的iPhone

在 2020年6月23日，下午6:13，daizeng.yang <notifications@github.com> 写道：

﻿

好的，谢谢啦





------------------ 原始邮件 ------------------
发件人: 健了个平 <notifications@github.com&gt;
发送时间: 2020年6月23日 18:12
收件人: Rogue24/JPImageresizerView <JPImageresizerView@noreply.github.com&gt;
抄送: daizeng.yang <316917975@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Rogue24/JPImageresizerView] 有支持微调旋转吗？ (#20)

**Comment by jianmu297** [comment]
这个功能感觉蛮重要的，作者现在有空考虑下吗

**Comment by ywdonga** [comment]
这个好像是小红书的功能，好多App抄小红书，好期待这个

**Comment by Rogue24** [comment]
小红书没有手指拖拽的 这个我可以之后写个demo哈

发自我的iPhone

在 2020年12月9日，上午9:16，ywdonga <notifications@github.com> 写道：

﻿

这个好像是小红书的功能，好多App抄小红书，好期待这个

**Comment by ywdonga** [comment]
小红书好像有45度旋转，大佬什么时候弄个这个功能 😊

**Comment by Rogue24** [comment]
迟些我高仿一个小红书的 应该周末发布哈～最近忙着

发自我的iPhone

在 2020年12月14日，下午9:05，ywdonga <notifications@github.com> 写道：

﻿

小红书好像有45度旋转，大佬什么时候弄个这个功能 😊

**Comment by Rogue24** [comment]
我的GitHub上有个小红书的裁剪demo 需要的话可以看看

发自我的iPhone

在 2020年12月14日，下午9:05，ywdonga <notifications@github.com> 写道：

﻿

小红书好像有45度旋转，大佬什么时候弄个这个功能 😊

**Comment by Rogue24** [comment]
小红书45度自定义旋转裁剪功能：https://github.com/Rogue24/JPCrop
