### ISSUE TITLE
下载项目文件略大，能否精简多媒体资源，可能对网络不好的下载不是很友好

### ISSUE THREAD

**Issue by hms040717007** [Rogue24/JPImageresizerView#21]

**Comment by Rogue24** [comment]
应该是一些素材资源文件过大了 sorry 我删掉一些

发自我的iPhone

在 2020年7月15日，上午11:18，HuangMS-War <notifications@github.com> 写道：

﻿

**Comment by Rogue24** [comment]
删减了😄

发自我的iPhone

在 2020年7月15日，上午11:25，周 健平 <zhoujianping24@hotmail.com> 写道：

﻿ 应该是一些素材资源文件过大了 sorry 我删掉一些

发自我的iPhone

在 2020年7月15日，上午11:18，HuangMS-War <notifications@github.com> 写道：

﻿
