### ISSUE TITLE
不好意思还有一个问题，我还要做什么才能显示？

### ISSUE THREAD

**Issue by hms040717007** [Rogue24/JPImageresizerView#22]
@interface EditImageViewController ()

{
    JPImageresizerView *_imageresizerView;
}

@end

@implementation EditImageViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // 注意：iOS11以下的系统，所在的controller最好设置automaticallyAdjustsScrollViewInsets为NO，不然就会随导航栏或状态栏的变化产生偏移
    if (@available(iOS 11.0, *)) {
        
    } else {
        self.automaticallyAdjustsScrollViewInsets = NO;
    }
    
    [self addSubviews];
    
}

- (void)addSubviews {
    [self.view addSubview:_imageresizerView];
}

- (JPImageresizerConfigure *)configure {
    if (_configure == nil) {
        self.editImage = [UIImage imageNamed:@"Kobe.jpg"];
        _configure = [JPImageresizerConfigure defaultConfigureWithResizeImage:self.editImage
                                                                         make:^(JPImageresizerConfigure *configure) {
            configure
             .jp_maskAlpha(0.5)
             .jp_frameType(JPConciseFrameType)
             .jp_isClockwiseRotation(YES)
             .jp_animationCurve(JPAnimationCurveEaseOut)
            .jp_viewFrame([UIScreen mainScreen].bounds);
        }];
    }
    
    return _configure;
}

- (JPImageresizerView *)imageresizerView {
    if (_imageresizerView == nil) {
        kWEAK_SELF
        
        _imageresizerView = [JPImageresizerView imageresizerViewWithConfigure:self.configure
                                                    imageresizerIsCanRecovery:^(BOOL isCanRecovery) {
            
            
        }
                                                 imageresizerIsPrepareToScale:^(BOOL isPrepareToScale) {
            
        }];
        
    }
    
    return _imageresizerView;
}

**Comment by Rogue24** [comment]
addsubview那里要用self. 用_不会触发懒加载

发自我的iPhone

在 2020年7月15日，下午12:03，HuangMS-War <notifications@github.com> 写道：

﻿

@interface<https://github.com/interface> EditImageViewController ()

{
JPImageresizerView *_imageresizerView;
}

@EnD<https://github.com/EnD>

@implementation<https://github.com/implementation> EditImageViewController

  *   (void)viewDidLoad {
[super viewDidLoad];
// 注意：iOS11以下的系统，所在的controller最好设置automaticallyAdjustsScrollViewInsets为NO，不然就会随导航栏或状态栏的变化产生偏移
if (@available<https://github.com/available>(iOS 11.0, *)) {

} else {
self.automaticallyAdjustsScrollViewInsets = NO;
}

[self addSubviews];

}

  *   (void)addSubviews {
[self.view addSubview:_imageresizerView];
}

  *   (JPImageresizerConfigure *)configure {
if (_configure == nil) {
self.editImage = [UIImage imageNamed:@"Kobe.jpg"];
_configure = [JPImageresizerConfigure defaultConfigureWithResizeImage:self.editImage
make:^(JPImageresizerConfigure *configure) {
configure
.jp_maskAlpha(0.5)
.jp_frameType(JPConciseFrameType)
.jp_isClockwiseRotation(YES)
.jp_animationCurve(JPAnimationCurveEaseOut)
.jp_viewFrame([UIScreen mainScreen].bounds);
}];
}

return _configure;
}

  *   (JPImageresizerView *)imageresizerView {
if (_imageresizerView == nil) {
kWEAK_SELF

  _imageresizerView = [JPImageresizerView imageresizerViewWithConfigure:self.configure
                                              imageresizerIsCanRecovery:^(BOOL isCanRecovery) {


  }
                                           imageresizerIsPrepareToScale:^(BOOL isPrepareToScale) {

  }];


}

return _imageresizerView;
}
