### ISSUE TITLE
您好请问，初始化裁剪框变为正方形，需要怎么设置？

### ISSUE THREAD

**Issue by hms040717007** [Rogue24/JPImageresizerView#23]

**Comment by Rogue24** [comment]
[cid:710E56E4-AE23-4F27-9DDD-E68A8A33F18D]

发自我的iPhone

在 2020年7月16日，上午11:17，HuangMS-War <notifications@github.com> 写道：

﻿

**Comment by hms040717007** [comment]
你发的[cid:710E56E4-AE23-4F27-9DDD-E68A8A33F18D]，什么意思？
还有就是点击你的demo（更换比例，更换样式）按钮闪退，更换素材按钮无反应

**Comment by Rogue24** [comment]
闪退信息是啥

发自我的iPhone

在 2020年7月16日，下午2:00，HuangMS-War <notifications@github.com> 写道：

﻿

你发的[cid:710E56E4-AE23-4F27-9DDD-E68A8A33F18D]，什么意思？
还有就是点击你的demo（更换比例，更换样式）按钮闪退，更换素材按钮无反应

**Comment by Rogue24** [comment]
[JPImageresizerConfigure defaultConfigureWithResizeImage:nil make:^(JPImageresizerConfigure *configure) {

        configure

        .jp_resizeWHScale(1)

        .jp_isArbitrarilyInitial(NO);

    }];

发自我的iPhone

在 2020年7月16日，下午2:23，周 健平 <zhoujianping24@hotmail.com> 写道：

﻿ 闪退信息是啥

发自我的iPhone

在 2020年7月16日，下午2:00，HuangMS-War <notifications@github.com> 写道：

﻿

你发的[cid:710E56E4-AE23-4F27-9DDD-E68A8A33F18D]，什么意思？
还有就是点击你的demo（更换比例，更换样式）按钮闪退，更换素材按钮无反应
