### ISSUE TITLE
能否增加拍摄视频功能

### ISSUE THREAD

**Issue by iOSchuang** [Rogue24/JPImageresizerView#24]
当前是选择本地视频进行编辑，能否增加拍摄视频时，给出一个视频宽高比，进行视频拍摄。还有编辑视频长度，获取封面等功能，类似于微信视频号的功能。谢谢

**Comment by Rogue24** [comment]
微信那种效果很简单，你设置ScrollView为不可交互和contentInsets的左右间距设置为0就跟微信的差不多效果了，目前要在此工程上改成跟微信完全一样还得花一段时间，建议UI重新写，裁剪的代码你可以参考JPImageresizerTool的裁剪方法

发自我的iPhone

在 2020年7月29日，下午7:44，CoderLee <notifications@github.com> 写道：

﻿

当前是选择本地视频进行编辑，能否增加拍摄视频时，给出一个视频宽高比，进行视频拍摄。还有编辑视频长度，获取封面等功能，类似于微信视频号的功能。谢谢

**Comment by Rogue24** [comment]
这种效果我之后会在Demo上加上 谢谢您的建议

发自我的iPhone

在 2020年7月29日，下午8:10，周 健平 <zhoujianping24@hotmail.com> 写道：

﻿微信那种效果很简单，你设置ScrollView为不可交互和contentInsets的左右间距设置为0就跟微信的差不多效果了，目前要在此工程上改成跟微信完全一样还得花一段时间，建议UI重新写，裁剪的代码你可以参考JPImageresizerTool的裁剪方法

发自我的iPhone

在 2020年7月29日，下午7:44，CoderLee <notifications@github.com> 写道：

﻿

当前是选择本地视频进行编辑，能否增加拍摄视频时，给出一个视频宽高比，进行视频拍摄。还有编辑视频长度，获取封面等功能，类似于微信视频号的功能。谢谢

**Comment by iOSchuang** [comment]
裁剪功能已经很完善了，辛苦啦

**Comment by Rogue24** [comment]
谢谢谢谢

发自我的iPhone

在 2020年7月30日，上午9:31，CoderLee <notifications@github.com> 写道：

﻿

裁剪功能已经很完善了，辛苦啦
