### ISSUE TITLE
裁剪图片能否长宽同比例，按照减少像素？

### ISSUE THREAD

**Issue by 295060456** [Rogue24/JPImageresizerView#25]

**Comment by 295060456** [comment]
我在你的demo里面找了半天，发现要手动进行裁剪才会输出，所以我移步☞https://github.com/KirstenDunst/CSXImageCompress/issues

**Comment by Rogue24** [comment]
缩小了不就是比原图尺寸还大吗

发自我的iPhone

在 2020年8月7日，下午3:00，Whiskey_On_The_Rocks <notifications@github.com> 写道：

﻿

我在你的demo里面找了半天，发现要手动进行裁剪才会输出，所以我移步☞https://github.com/KirstenDunst/CSXImageCompress/issues

**Comment by 295060456** [comment]
我今天下午一直在调这个，也对比了比较好的github demo
  pod 'YQImageCompressor' # https://github.com/976431yang/YQImageCompressor

这个可以 。

**Comment by Rogue24** [comment]
原来你指的是压缩啊，有的啊，裁剪的时候可以选压缩比例的，具体可以看看[文档-裁剪]那里的API说明
________________________________
发件人: Whiskey_On_The_Rocks <notifications@github.com>
发送时间: 2020年8月7日 8:30
收件人: Rogue24/JPImageresizerView <JPImageresizerView@noreply.github.com>
抄送: 健了个平 <zhoujianping24@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [Rogue24/JPImageresizerView] 裁剪图片能否长宽同比例，按照减少像素？ (#25)


我今天下午一直在调这个，也对比了比较好的github demo
pod 'YQImageCompressor' # https://github.com/976431yang/YQImageCompressor

这个可以 。

―
