### ISSUE TITLE
关于缩放裁剪。

### ISSUE THREAD

**Issue by longjianjiang** [Rogue24/JPImageresizerView#28]
有一张比较宽的图片，我用下面这个方法裁成`3:4`, 发现图片变小了，应该是没有缩放直接裁剪导致的。

```swift
   //将图片裁剪成指定比例（多余部分自动删除）
    func crop(ratio: CGFloat) -> UIImage {
        //计算最终尺寸
        var newSize:CGSize!
        if size.width/size.height > ratio {
            newSize = CGSize(width: size.height * ratio, height: size.height)
        }else{
            newSize = CGSize(width: size.width, height: size.width / ratio)
        }
     
        ////图片绘制区域
        var rect = CGRect.zero
        rect.size.width  = size.width
        rect.size.height = size.height
        rect.origin.x    = (newSize.width - size.width ) / 2.0
        rect.origin.y    = (newSize.height - size.height ) / 2.0
         
        //绘制并获取最终图片
        UIGraphicsBeginImageContext(newSize)
        draw(in: rect)
        let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
         
        return scaledImage!
    }
```

想问一下，需要做到demo里编辑页面里选固定尺寸然后生成裁剪后的图片，有提供代码直接操作的方式嘛。

**Comment by Rogue24** [comment]
可以 你加我扣扣吧 我发给你

发自我的iPhone

在 2020年9月14日，下午9:15，longjianjiang <notifications@github.com> 写道：

﻿

有一张比较宽的图片，我用下面这个方法裁成3:4, 发现图片变小了，应该是没有缩放直接裁剪导致的。

   //将图片裁剪成指定比例（多余部分自动删除）
    func crop(ratio: CGFloat) -> UIImage {
        //计算最终尺寸
        var newSize:CGSize!
        if size.width/size.height > ratio {
            newSize = CGSize(width: size.height * ratio, height: size.height)
        }else{
            newSize = CGSize(width: size.width, height: size.width / ratio)
        }

        ////图片绘制区域
        var rect = CGRect.zero
        rect.size.width  = size.width
        rect.size.height = size.height
        rect.origin.x    = (newSize.width - size.width ) / 2.0
        rect.origin.y    = (newSize.height - size.height ) / 2.0

        //绘制并获取最终图片
        UIGraphicsBeginImageContext(newSize)
        draw(in: rect)
        let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return scaledImage!
    }

想问一下，需要做到demo里编辑页面里选固定尺寸然后生成裁剪后的图片，有提供代码直接操作的方式嘛。
