### ISSUE TITLE
请问可以支持手势裁剪吗

### ISSUE THREAD

**Issue by kivenZheng** [Rogue24/JPImageresizerView#29]
就是在图上画一个图形，而且这个图形可以调整。

**Comment by Rogue24** [comment]
这种你可以实现一个滑板 画出那个图案再转成png图片就可以实现了

发自我的iPhone

在 2020年9月28日，下午4:17，kivenZheng <notifications@github.com> 写道：

﻿

就是在图上画一个图形，而且这个图形可以调整。

**Comment by kivenZheng** [comment]
1. 

- 

> ### **_`[](url)`_**
