### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by omiz** [Rogue24/JPImageresizerView#3]
Will you support those of us who speaks English in either the documentation or the readme file?

**Comment by Rogue24** [comment]
OK, no problem. Give me time.
________________________________
发件人: Omar Allaham <notifications@github.com>
发送时间: 2019年2月13日 8:22
收件人: Rogue24/JPImageresizerView
抄送: Subscribed
主题: [Rogue24/JPImageresizerView] English documentation (#3)


Will you support those of us who speaks English in either the documentation or the readme file?

―

**Comment by omiz** [comment]
I'm ready to help if you need anything

**Comment by Rogue24** [comment]
Thank you. It's just a little thing.😜
________________________________
发件人: Omar Allaham <notifications@github.com>
发送时间: 2019年2月14日 7:09
收件人: Rogue24/JPImageresizerView
抄送: 健了个平; Comment
主题: Re: [Rogue24/JPImageresizerView] English documentation (#3)


I'm ready to help if you need anything

**Comment by Rogue24** [comment]
Here is the English document: https://www.jianshu.com/p/5600da5c9bf6.
PS: My English level is not very good, maybe some of the writing is not clear enough, please forgive me.😅
JPImageresizerView Specification Document<https://www.jianshu.com/p/5600da5c9bf6>
GitHub：https://github.com/Rogue24/JPImageresizerView JPImageresizerView Brief introduction A smal...
www.jianshu.com


________________________________
发件人: Omar Allaham <notifications@github.com>
发送时间: 2019年2月14日 7:09
收件人: Rogue24/JPImageresizerView
抄送: 健了个平; Comment
主题: Re: [Rogue24/JPImageresizerView] English documentation (#3)


I'm ready to help if you need anything

**Comment by omiz** [comment]
Thank you a lot
