### ISSUE TITLE
可以支持默认进入图片铺满，裁剪框在中间固定大小的正方形区域，而不是整个图片大小？

### ISSUE THREAD

**Issue by fanzK12** [Rogue24/JPImageresizerView#30]

**Comment by fanzK12** [comment]
类似微信上传图像，裁剪框默认选中中间部分正方形区域

**Comment by Rogue24** [comment]
初始化配置时这样设置一下即可[cid:0dfa923d-8e24-4450-946e-b165f174e56a]
________________________________
发件人: fanzK12 <notifications@github.com>
发送时间: 2020年10月30日 9:37
收件人: Rogue24/JPImageresizerView <JPImageresizerView@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Rogue24/JPImageresizerView] 可以支持默认进入图片铺满，裁剪框在中间固定大小的正方形区域，而不是整个图片大小？ (#30)


Closed #30<https://github.com/Rogue24/JPImageresizerView/issues/30>.

―
