### ISSUE TITLE
裁剪问题

### ISSUE THREAD

**Issue by CoderSwitch** [Rogue24/JPImageresizerView#34]
我们有个需求，要求裁剪的图片为2寸照片，像素为413*626,这个用咱的sdk的话需要怎么设置。求解答

**Comment by Rogue24** [comment]
@CoderSwitch 裁剪方法里面有个compressScale参数可以设置裁剪比例，可以通过计算算出这个比例是多少，例如以宽度为例：compressScale = 413 / width（这个比例我里面会自动限制在0~1的范围内），这样就应该能达到你的需求吧

**Comment by CoderSwitch** [comment]
谢谢作者的认真解答。
