### ISSUE TITLE
裁剪比例来回切换会导致图片无限放大

### ISSUE THREAD

**Issue by jxa184971** [Rogue24/JPImageresizerView#4]
`- (void)updateImageOriginFrameWithDirection:(JPImageresizerRotationDirection)rotationDirection`

这个方法里面获取的imageView的宽高（baseImageW、baseImageH）是不会变的，就会导致即使图片宽高已经超过裁剪框，图片也会自动放大。我觉得是不是需要乘以一下当前scrollView的`zoomScale`更合适一些？

**Comment by Rogue24** [comment]
首先谢谢你反馈 我下班之后检查一下 到时候再通知您哈！
________________________________
发件人: Yichuan Huang <notifications@github.com>
发送时间: 2019年3月20日 6:56
收件人: Rogue24/JPImageresizerView
抄送: Subscribed
主题: [Rogue24/JPImageresizerView] 裁剪比例来回切换会导致图片无限放大 (#4)


- (void)updateImageOriginFrameWithDirection:(JPImageresizerRotationDirection)rotationDirection

这个方法里面获取的imageView的宽高（baseImageW、baseImageH）是不会变的，就会导致即使图片宽高已经超过裁剪框，图片也会自动放大。我觉得是不是需要乘以一下当前scrollView的zoomScale更合适一些？

―

**Comment by Rogue24** [comment]
您好 放大的确是为了不超过裁剪框 乘以zoomScale貌似不太合适
________________________________
发件人: Yichuan Huang <notifications@github.com>
发送时间: 2019年3月20日 6:56
收件人: Rogue24/JPImageresizerView
抄送: Subscribed
主题: [Rogue24/JPImageresizerView] 裁剪比例来回切换会导致图片无限放大 (#4)


- (void)updateImageOriginFrameWithDirection:(JPImageresizerRotationDirection)rotationDirection

这个方法里面获取的imageView的宽高（baseImageW、baseImageH）是不会变的，就会导致即使图片宽高已经超过裁剪框，图片也会自动放大。我觉得是不是需要乘以一下当前scrollView的zoomScale更合适一些？

―

**Comment by jxa184971** [comment]
在您给出的样例中，"浅色毛玻璃遮罩"这个类目下，如果来回多次点击"1：1"和"16：9"按钮，就会发生我说的情况，图片会无限放大下去。您可以按照这个方式试试看。

**Comment by Rogue24** [comment]
您好 当初这样设计是为了防止在边界时切换比例时能刚好适配到边界不超出。
________________________________
发件人: Yichuan Huang <notifications@github.com>
发送时间: 2019年3月25日 9:46
收件人: Rogue24/JPImageresizerView
抄送: 健了个平; Comment
主题: Re: [Rogue24/JPImageresizerView] 裁剪比例来回切换会导致图片无限放大 (#4)


在您给出的样例中，"浅色毛玻璃遮罩"这个类目下，如果来回多次点击"1：1"和"16：9"按钮，就会发生我说的情况，图片会无限放大下去。您可以按照这个方式试试看。

―
