### ISSUE TITLE
某个视频文件裁剪失败

### ISSUE THREAD

**Issue by abchenyu** [Rogue24/JPImageresizerView#41]
视频文件：
https://user-images.githubusercontent.com/2410637/146344146-2677d41f-f169-42d6-af3d-829170fbf2f1.mp4

打印session.error：
Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12769)

尝试了把视频timeRange设置短一点可以裁剪成功，请教下这是啥问题？

**Comment by Rogue24** [comment]
@abchenyu 这是远程视频吗？我目前没对远程视频做适配的，要不试试先缓存到本地，再从本地获取？

**Comment by abchenyu** [comment]
> @abchenyu 这是远程视频吗？我目前没对远程视频做适配的，要不试试先缓存到本地，再从本地获取？

不是远程视频，是把这个视频文件放在相册操作的。

**Comment by Rogue24** [comment]
@abchenyu 这个问题目前还不太清楚为何 也有可能是视频文件的问题 我再去探究一下先

**Comment by abchenyu** [comment]
> @abchenyu 这个问题目前还不太清楚为何 也有可能是视频文件的问题 我再去探究一下先

目前尝试了设置audioMix可以成功，具体啥原因没搞明白

**Comment by Rogue24** [comment]
@abchenyu 请问怎么设置呢🥲

**Comment by abchenyu** [comment]
> @abchenyu 请问怎么设置呢🥲

    AVMutableAudioMix *audioMix = [AVMutableAudioMix audioMix];
    // 插入音频轨道
    AVAssetTrack *audioTrack = [asset tracksWithMediaType:AVMediaTypeAudio].firstObject;
    if (audioTrack) {
        AVMutableCompositionTrack *audioCompositionTrack = [composition addMutableTrackWithMediaType:AVMediaTypeAudio preferredTrackID:kCMPersistentTrackID_Invalid];
        [audioCompositionTrack insertTimeRange:timeRange ofTrack:audioTrack atTime:kCMTimeZero error:nil];
        
        AVMutableAudioMixInputParameters *inputParameter = [AVMutableAudioMixInputParameters audioMixInputParametersWithTrack: audioCompositionTrack];
        [inputParameter setVolume:1 atTime:kCMTimeZero];
        audioMix.inputParameters = @[inputParameter];
    }
    ...
    session.audioMix = audioMix;

**Comment by Rogue24** [comment]
@abchenyu 十分蟹蟹٩('ω')و 我去适配一下
