### ISSUE TITLE
使用swift构建pod私有库时，引入"JPImageresizerView"，编译错误

### ISSUE THREAD

**Issue by FutureZhang** [Rogue24/JPImageresizerView#47]
**当我使用swift构建自己的pod私有库时，引入依赖s.dependency 'JPImageresizerView'，编译错误，分两大类错误：**
1. 在我自己的xxx.swift文件中使用 import JPImageresizerView，报错”Could not build Objective-C module 'JPImageresizerView'“；
2. 在JPImageresizerView pod组件内部如：#import <JPImageresizerTypedef.h>等使用尖角号的方式引入头文件的地方，报错：'JPImageresizerTypedef.h' file not found with <angled> include; use "quotes" instead

**我的尝试**
当我尝试把JPImageresizerView组件内所有以尖角号<>引用头文件的方式改为以双引号""后，例如：把#import <JPImageresizerTypedef.h>改为#import "JPImageresizerTypedef.h"后，我的私有pod组件库编译顺利通过了，还请大佬抽时间验证修复下这个问题 @Rogue24

**Comment by FutureZhang** [comment]
>

**Comment by Rogue24** [comment]
@FutureZhang 已经修正，真的十分感谢！
