### ISSUE TITLE
设置固定比例裁剪4:3  3:4 1:1   点击3:4  在点击重置时 无响应  其他两个比例都重置可以的。

### ISSUE THREAD

**Issue by LAnqxpp** [Rogue24/JPImageresizerView#49]

**Comment by LAnqxpp** [comment]
点击3:4  在点击重置时 无响应  log
17:06:55 -[JPImageresizerView setResizeWHScale:isToBeArbitrarily:animated:] 第694行: jp_tip: 裁剪区域预备缩放至适合位置，裁剪宽高比暂不可设置，此时应该将设置按钮设为不可点或隐藏

还有个问题就是 每次比例裁剪时 能在原图上裁剪，不是在上一次图上进行裁剪。

**Comment by Rogue24** [comment]
@LAnqxpp 这个你得用回原图传入哦 并且你得保存上一次裁剪的历史记录 有这个api的
