### ISSUE TITLE
裁剪bug

### ISSUE THREAD

**Issue by madonya** [Rogue24/JPImageresizerView#52]
复现步骤
1、设定翻转为垂直翻转
2、翻转
3、设置旋转为逆时针
4、旋转
5、完成
此时获得的图片与预览不符

**Comment by madonya** [comment]
https://github.com/Rogue24/JPImageresizerView/blob/0ecaacab1b5c774c5d8b9dd1f3f1d6cadb1f392f/JPImageresizerView/Classes/JPImageresizerView.m#L919

把这一行改成 `BOOL isNormal = YES;`可以解决，这样先翻转，在旋转，旋转的方向在视觉上跟设置的是一致的。
造成的原因应该是最后裁剪图片的时候，你先处理的旋转，后处理的翻转。但是先翻转后旋转，跟先旋转后翻转得到的图片是不一致的，未做区分。

**Comment by Rogue24** [comment]
@madonya 感谢反馈和指正！
