### ISSUE TITLE
[Bug]保存配置，恢复配置后，不进行操作，recoveryByxxxxx无效

### ISSUE THREAD

**Issue by ghosthk** [Rogue24/JPImageresizerView#53]
1. 长图裁剪为方图/圆图。
2. 保存配置。
3. 恢复配置，不进行任何滑动操作。
4. 然后执行恢复原图，recoveryByInitialResizeWHScale失效，提示@"jp_tip: 已经是初始状态，不需要重置"

问题是由于恢复后，不进行操作 self.frameView.isCanRecovery 为false引起。
暂时解决方案为:  强制设置isCanRecovery为true，然后执行恢复。
```
imageView.frameView.setValue(true, forKeyPath: "isCanRecovery")
imageView.recovery(toTargetResizeWHScale: 0, isToBeArbitrarily: true)
```

**Comment by Rogue24** [comment]
@ghosthk 感谢反馈 会尽快修复的

**Comment by Rogue24** [comment]
@ghosthk 现在已更新为重置方法不再判断那属性了。
