### ISSUE TITLE
能不能出一个功能

### ISSUE THREAD

**Issue by wdq123550** [Rogue24/JPImageresizerView#55]
这个功能可以记录上一次裁剪框调整的样子，比如我在A页面传入图片，然后调整好需要裁剪的区域了。然后dismiss A页面，然后用户想重新对这个图片裁剪，再次present A页面的时候 裁剪的区域还是上次调整的样子。

**Comment by wdq123550** [comment]
https://user-images.githubusercontent.com/20955893/227128138-784b019a-1e0d-4e94-b81d-57262fccdc6f.mp4

类似视频这样

**Comment by Rogue24** [comment]
@wdq123550 有的 你可以看看demo 可以缓存上一次的裁剪进度
