### ISSUE TITLE
当固定裁剪比例的值不是1:1的时候，点击旋转之后，裁剪框的视图比例与设置的裁剪比列不符

### ISSUE THREAD

**Issue by Bob-GGB** [Rogue24/JPImageresizerView#58]
self.imageresizerView.resizeWHScale = 1.5;
旋转的时候，裁剪框视图也跟着旋转，导致裁剪框的视图比例与设置的裁剪比列不符
视频演示如下：

https://github.com/Rogue24/JPImageresizerView/assets/20783580/4a78bee2-3003-4be9-861d-2105cbd19018

**Comment by gaoguanbao** [comment]
self.imageresizerView.resizeWHScale = 1.5;

**Comment by gaoguanbao** [comment]
注释frameView的旋转代码，可以解决，希望大哥可以兼容一下
![image](https://github.com/Rogue24/JPImageresizerView/assets/20783580/70cb4a7a-ea8d-4a79-852a-185bff9f77f9)

**Comment by Rogue24** [comment]
@Bob-GGB 有个isArbitrarily属性，你可以设置为NO就会保持原比例了

**Comment by Bob-GGB** [comment]
好的，谢谢
