### ISSUE TITLE
希望支持手势可以放大缩小图片以及设置裁剪框的最大frame

### ISSUE THREAD

**Issue by luowen1991** [Rogue24/JPImageresizerView#6]

**Comment by Rogue24** [comment]
呃 不太理解 现在是可以通过手势放大缩小。。
________________________________
发件人: 罗文 <notifications@github.com>
发送时间: 2019年4月12日 10:00
收件人: Rogue24/JPImageresizerView
抄送: Subscribed
主题: Re: [Rogue24/JPImageresizerView] 希望支持手势可以放大缩小图片以及设置裁剪框的最大frame (#6)


Closed #6<https://github.com/Rogue24/JPImageresizerView/issues/6>.

―
