### ISSUE TITLE
一直说我的gif不是gif

### ISSUE THREAD

**Issue by Garenge** [Rogue24/JPImageresizerView#62]
正常集成, gif文件导入, 一直说我不是gif文件, 请问怎么搞

**Comment by Rogue24** [comment]
@Garenge 文件可以发我看一下吗

**Comment by Garenge** [comment]
我创建config用的defaultConfigureWithImage, 一直说不是gif, 然后我同事用的defaultConfigureWithImageData, 就识别成了gif, 这个感觉应该加个注释, 你image方法是取的帧图判断gif, data用的是[data getBytes:&c length:1]; return c == 0x47;

是我自己没注意, 现在已经解决了

**Comment by Rogue24** [comment]
@Garenge 感谢反馈 后续加上
