### ISSUE TITLE
挺不错的，setupScorllView这个方法的x貌似算错了吧 不需要加_contentInsets.left吧

### ISSUE THREAD

**Issue by 964562398** [Rogue24/JPImageresizerView#7]

**Comment by Rogue24** [comment]
这个是为了可以让外界设置额外边距😃

发自我的 iPhone

在 2019年4月28日，下午3:06，WildWang <notifications@github.com<mailto:notifications@github.com>> 写道：

**Comment by 964562398** [comment]
你去JPTableViewController 将例子用的contentInsets 的left和right改一下，比如分别都设置40或者10看看（目前你设置的是0）

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo的作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
