### ISSUE TITLE
裁剪界面，图片可以无限放大

### ISSUE THREAD

**Issue by WOHANGO** [Rogue24/JPImageresizerView#8]
正常下一张图片不可能无限方案，可以参考苹果本机相册放大效果，放大到一定程度会自动收缩回去。

**Comment by Rogue24** [comment]
好的 你可以改一下源码设置一下最大倍数

发自我的iPhone

在 2019年11月12日，下午4:38，wuzihang <notifications@github.com> 写道：

﻿

正常下一张图片不可能无限方案，可以参考苹果本机相册放大效果，放大到一定程度会自动收缩回去。

**Comment by Rogue24** [comment]
已新增maximumZoomScale选项 初始化时可以自定义 默认10~
